import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from '@/lib/AuthContext';
import { updateUser } from '@/lib/localStorage';

const LanguageContext = createContext(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return { language: 'pl', setLanguage: () => {}, t: (key) => key };
  }
  return context;
}

export function LanguageProvider({ children }) {
  const { user, checkSession } = useAuth();
  const [language, setLanguage] = useState(() => {
    // Initialize from localStorage
    const saved = localStorage.getItem("appLanguage");
    return saved === 'en' ? 'en' : 'pl';
  });
  const [translations, setTranslations] = useState({});
  const [isLoading, setIsLoading] = useState(true);

  const normalizeLanguage = (value) => (value === 'en' ? 'en' : 'pl');

  // Load translations whenever language changes
  useEffect(() => {
    const lang = language || 'pl';
    const allTranslations = {
      pl: {
        // Navigation
        dashboard: "Dashboard",
        journal: "Dziennik",
        notes: "Moje notatki",
        calendar: "Kalendarz",
        analytics: "Analiza",
        accounts: "Konta",
        strategies: "Strategie",
        goals: "Cele",
        settings: "Ustawienia",
        billing: "Subskrypcja",
        
        // Common
        save: "Zapisz",
        cancel: "Anuluj",
        progressTracker: "Progress Tracker",
        edit: "Edytuj",
        delete: "Usuń",
        add: "Dodaj",
        added: "Dodano",
        remove: "Usuń",
        change: "Zmień",
        view: "Podgląd",
        search: "Szukaj",
        filter: "Filtruj",
        export: "Eksportuj",
        import: "Importuj",
        loading: "Ładowanie...",
        noData: "Brak danych",
        actions: "Akcje",
        date: "Data",
        notes: "Notatki",
        color: "Kolor",
        priority: "Priorytet",
        description: "Opis",
        loadDataError: "Błąd przy ładowaniu danych",
        userNotAuthenticated: "Użytkownik nie jest zalogowany",
        requiredFieldsSymbolDate: "Uzupełnij wymagane pola: symbol, data",
        requiredFieldsSymbolEntrySize: "Uzupełnij wymagane pola: symbol, cena wejścia, wielkość pozycji",
        errorSavingTrade: "Błąd zapisu transakcji",
        selectAccountPlaceholder: "-- Wybierz konto --",
        noAccountsAvailable: "Brak dostępnych kont",
        selectStrategyPlaceholder: "-- Wybierz strategię --",
        noStrategiesAvailable: "Brak dostępnych strategii",
        notesPlaceholder: "Dodatkowe notatki...",
        notesTitle: "Moje notatki",
        notesSubtitle: "Organizuj pomysly, checklisty i plany jak w nowoczesnym notatniku",
        notesNew: "Nowa notatka",
        notesNewChecklist: "Nowa lista",
        notesNewPlan: "Nowy plan",
        notesExport: "Eksport",
        notesImport: "Import",
        notesSearch: "Szukaj notatek, zadan lub tagow...",
        notesAll: "Wszystkie",
        notesNotes: "Notatki",
        notesChecklists: "Checklisty",
        notesPlans: "Plany",
        notesLibrary: "Biblioteka",
        notesPages: "Strony",
        notesStructure: "Struktura",
        notesNotebooks: "Notatniki",
        notesSections: "Sekcje",
        notesSelectNotebook: "Wybierz notatnik",
        notesSelectSection: "Wybierz sekcje",
        notesNewNotebook: "Nowy notatnik",
        notesNewSection: "Nowa sekcja",
        notesRenameNotebook: "Zmien nazwe notatnika",
        notesRenameSection: "Zmien nazwe sekcji",
        notesDefaultNotebook: "Glowny notatnik",
        notesDefaultSection: "Ogolne",
        notesAdd: "Dodaj",
        notesAddPage: "Dodaj strone",
        notesAddSubpage: "Dodaj podstrone",
        notesAddSection: "Dodaj sekcje",
        notesDeleteSection: "Usun sekcje",
        notesRenamePage: "Zmien nazwe strony",
        notesRenameSectionPrompt: "Podaj nowa nazwe sekcji",
        notesRenamePagePrompt: "Podaj nowa nazwe strony",
        notesEmpty: "Brak notatek. Stworz pierwsza notatke lub plan.",
        notesUntitled: "Bez tytulu",
        notesChecklistItems: "Lista zadan",
        notesNoPreview: "Brak podgladu",
        notesEditor: "Edytor",
        notesPin: "Przypnij",
        notesUnpin: "Odepnij",
        notesDelete: "Usun",
        notesSelect: "Wybierz notatke z listy lub utworz nowa.",
        notesSelectFirst: "Najpierw wybierz notatke lub utworz nowa.",
        notesTitleLabel: "Tytul",
        notesTitlePlaceholder: "Tytul notatki",
        notesBody: "Tresc",
        notesBodyPlaceholder: "Piszesz tutaj. Wspieramy pomysly, plany i checklisty...",
        notesChecklist: "Checklist",
        notesAddTask: "Dodaj zadanie",
        notesChecklistEmpty: "Brak zadan. Dodaj pierwszy punkt.",
        notesTaskPlaceholder: "Nowe zadanie...",
        notesType_note: "Notatka",
        notesType_checklist: "Checklist",
        notesType_plan: "Plan",
        notesType: "Typ",
        notesStatus: "Status",
        notesStatus_active: "Aktywna",
        notesStatus_done: "Zakonczona",
        notesStatus_archived: "Archiwum",
        notesPriority: "Priorytet",
        notesPriority_low: "Niski",
        notesPriority_medium: "Sredni",
        notesPriority_high: "Wysoki",
        notesDueDate: "Termin",
        notesReminder: "Przypomnienie",
        notesReminderSet: "Przypomnienie ustawione",
        notesReminderSent: "Przypomnienie wyslane",
        notesReminderPermission: "Wlacz powiadomienia, aby dzialaly przypomnienia",
        notesReminderFallback: "Przypomnienie zapisane, ale powiadomienia sa wylaczone",
        notesTags: "Tagi",
        notesTagPlaceholder: "Dodaj tag...",
        notesAddTag: "Dodaj",
        notesNeedTag: "Wpisz nazwe tagu.",
        notesTagsEmpty: "Brak tagow",
        notesRemoveTag: "Usun tag",
        notesLinks: "Linki",
        notesLinkTitle: "Tytul linku",
        notesLinkUrl: "Adres URL",
        notesTableRows: "Podaj liczbe wierszy",
        notesTableCols: "Podaj liczbe kolumn",
        notesImageUrl: "Podaj adres obrazka",
        notesImageUploadError: "Nie udało się przesłać obrazka",
        notesAttachments: "Zalaczniki",
        notesAddAttachment: "Dodaj plik",
        notesAttachmentsEmpty: "Brak zalacznikow",
        notesRemoveAttachment: "Usun",
        notesAttachmentUploadError: "Nie udalo sie przeslac pliku",
        notesAddLink: "Dodaj link",
        notesNeedLink: "Wpisz adres linku.",
        notesLinksEmpty: "Brak linkow",
        notesNeedNotebookName: "Wpisz nazwe notatnika.",
        notesNeedSectionName: "Wpisz nazwe sekcji.",
        notesNewSectionPrompt: "Podaj nazwe nowej sekcji",
        notesNeedRenameSection: "Wpisz nowa nazwe sekcji.",
        notesDeleteBlockedNotebook: "Nie mozna usunac ostatniego notatnika.",
        notesDeleteBlockedSection: "Nie mozna usunac ostatniej sekcji.",
        notesImportInvalid: "Nieprawidlowy plik importu.",
        notesTaskDue: "Termin zadania",
        notesTaskNote: "Notatka do zadania",
        notesViewList: "Lista",
        notesViewGrid: "Siatka",
        notesViewTimeline: "Oś czasu",
        notesViewKanban: "Kanban",
        
        // Billing & Pricing
        billingTitle: "Subskrypcja Trade Log",
        billingSubtitle: "Zarzadzaj planem i funkcjami premium",
        billingPlanDesc: "Pełny dostęp do wszystkich funkcji tradingowych",
        billingPerMonth: "miesiąc",
        billing14DayTrial: "14 dni za darmo",
        billingIncluded: "Co otrzymujesz:",
        billingProFeature1: "Nieograniczony dziennik transakcji i analiza",
        billingProFeature2: "Zaawansowane wykresy i raporty wydajności",
        billingProFeature3: "Zarządzanie strategiami i celami",
        billingProFeature4: "Inteligentne notatki z AI i checklisty",
        billingProFeature5: "Eksport danych i backup w chmurze",
        billingProFeature6: "Wsparcie priorytetowe 24/7",
        billingActive: "Aktywna subskrypcja",
        billingManage: "Zarządzaj subskrypcją",
        billingStartTrial: "Rozpocznij 14-dniowy trial",
        billingNoCreditCard: "Nie wymaga karty kredytowej do rozpoczęcia trialu",
        billingStatusTitle: "Status subskrypcji",
        billingLoading: "Sprawdzanie statusu...",
        billingStatus: "Status: {status}",
        billingMissingPrice: "Brak skonfigurowanej ceny Stripe",
        billingCheckoutError: "Nie udalo sie otworzyc platnosci",
        billingPortalError: "Nie udalo sie otworzyc panelu subskrypcji",
        billingUpgradeNeeded: "Ta funkcja wymaga planu Pro",
        
        // Pricing Page
        pricingBadge: "Jedna prosta cena",
        pricingTitle: "Profesjonalny trading za $9.9/miesiąc",
        pricingSubtitle: "Wszystkie narzędzia potrzebne do rozwoju jako trader. Bez ukrytych kosztów.",
        pricingPlanDesc: "Pełny dostęp do wszystkich funkcji",
        pricingPerMonth: "miesiąc",
        pricing14DayTrial: "14 dni za darmo - bez karty",
        pricingInclude1: "Nieograniczona liczba transakcji i kont",
        pricingInclude2: "Zaawansowane analizy P&L, win rate i profit factor",
        pricingInclude3: "Inteligentne strategie i playbooki",
        pricingInclude4: "Moduł psychologii tradingu i dziennik emocji",
        pricingInclude5: "Automatyczny backup i eksport danych",
        pricingInclude6: "Wsparcie premium i regularne aktualizacje",
        pricingStartTrial: "Rozpocznij za darmo",
        pricingNoCreditCard: "Do trialu nie potrzebujesz karty kredytowej",
        pricingWhyChoose: "Dlaczego Trade Log?",
        pricingFeature1Title: "Pełna analiza wydajności",
        pricingFeature1Desc: "Szczegółowe statystyki, wykresy equity, analiza czasowa i wiele więcej",
        pricingFeature2Title: "Psychologia tradingu",
        pricingFeature2Desc: "Śledź emocje, jakość setupów i rozwój mentalny",
        pricingFeature3Title: "Zarządzanie celami",
        pricingFeature3Desc: "Ustaw cele, monitoruj postępy i buduj konsekwencję",
        pricingFeature4Title: "Strategie i playbooki",
        pricingFeature4Desc: "Dokumentuj swoje setups i analizuj ich skuteczność",
        pricingFeature5Title: "Bezpieczeństwo danych",
        pricingFeature5Desc: "Szyfrowanie end-to-end i automatyczne backupy",
        pricingFeature6Title: "Szybkie wsparcie",
        pricingFeature6Desc: "Odpowiadamy w 24h i dodajemy nowe funkcje na bieżąco",
        pricingCTATitle: "Gotowy na rozwój?",
        pricingCTADesc: "Dołącz do setek traderów, którzy używają Trade Log do budowania konsekwencji i poprawy wyników.",
        pricingGetStarted: "Zacznij za darmo",
        
        // Dashboard
        totalPL: "Całkowity P&L",
        winRate: "Win Rate",
        avgPL: "Średni P&L",
        profitFactor: "Profit Factor",
        totalTrades: "Transakcji",
        wins: "Wygrane",
        losses: "Przegrane",
        breakeven: "Breakeven",
        bestTrade: "Najlepszy trade",
        worstTrade: "Najgorszy trade",
        overviewOfYourTradingPerformance: "Przegląd Twojej wydajności tradingowej",
        from: "Z",
        perTrade: "Na transakcję",
        avgWinAvgLoss: "Średnia wygrana / Średnia przegrana",
        avgWin: "Średnia wygrana",
        avgLoss: "Średnia przegrana",
        averageWin: "Średnia wygrana",
        averageLoss: "Średnia przegrana",
        totalTradesLabel: "Łączne transakcje",
        plOverTime: "P&L w czasie",
        strategyPerformance: "Wydajność strategii",
        select: "Wybierz",
        myAccount: "Moje konto",
        allAccounts: "Wszystkie konta",
        filters: "Filtry",
        dateRange: "Zakres dat",
        last7Days: "Ostatnie 7 dni",
        last30Days: "Ostatnie 30 dni",
        last90Days: "Ostatnie 90 dni",
        lastImport: "Ostatni import",
        resync: "Odśwież",
        startMyDay: "Rozpocznij dzień",
        reset: "Resetuj",
        apply: "Zastosuj",
        dayWinRate: "Wygrane dziś %",
        zellaScore: "Wynik Zella",
        tradingScore: "Wynik Tradingowy",
        less: "Mniej",
        more: "Więcej",
        dailyNetCumulativePL: "Skumulowany dzienny P&L netto",
        netDailyPL: "Dzienny P&L netto",
        recentTrades: "Ostatnie transakcje",
        netPL: "P&L netto",
        accountBalance: "Saldo konta",
        drawdown: "Obsunięcie",
        tradeTimePerformance: "Wyniki według czasu",
        selectPlaceholder: "Wybierz...",
        winRatePercent: "Win Rate (%)",
        detailedPLAnalysis: "Szczegółowa analiza P&L",
        totalProfit: "Łączny zysk",
        totalLoss: "Łączna strata",
        plByWeekday: "P&L według dnia tygodnia",
        plBySymbol: "P&L według symbolu",
        detailedWinRateAnalysis: "Szczegółowa analiza Win Rate",
        ofAll: "wszystkich",
        streaks: "Serie",
        maxWins: "Max wygrane",
        maxLosses: "Max przegrane",
        winRateBySymbol: "Win Rate według symbolu",
        winsShort: "W",
        lossesShort: "L",
        breakevenShort: "BE",
        detailedAvgPLAnalysis: "Szczegółowa analiza średniego P&L",
        avgWinShort: "Śr. wygrana",
        avgLossShort: "Śr. przegrana",
        medianWin: "Mediana wygrana",
        medianLoss: "Mediana przegrana",
        avgPLByDirection: "Średni P&L według kierunku",
        longLabel: "Long",
        shortLabel: "Short",
        detailedProfitFactorAnalysis: "Szczegółowa analiza Profit Factor",
        pfExcellent: "Doskonały",
        pfGood: "Dobry",
        pfAcceptable: "Akceptowalny",
        pfNeedsImprovement: "Wymaga poprawy",
        tradeEfficiency: "Efektywność transakcji",
        detailedOutcomeAnalysis: "Szczegółowa analiza rozkładu wyników",
        distributionByTimeframe: "Rozkład według timeframe",
        zellaWinRate: "Win %",
        zellaProfit: "Zysk",
        zellaConsistency: "Spójność",
        zellaDrawdown: "Obsunięcie",
        zellaAvgWL: "Śr. W/L",
        advancedAnalytics: "Zaawansowana analiza",
        detailedAnalysisOfAllAspects: "Szczegółowa analiza wszystkich aspektów tradingu",
        outcomeDistribution: "Rozkład wyników",
        directionDistribution: "Rozkład kierunków",
        equityCurve: "Krzywa kapitału",
        results: "Wyniki",
        weekly: "Tygodniowo",
        monthly: "Miesięcznie",
        yearly: "Rocznie",
        daily: "Dziennie",
        insightOutcomeMost: "Najwięcej wyników:",
        insightOutcomeEmpty: "Brak danych do wniosków",
        insightDirectionBest: "Najlepszy kierunek:",
        insightDirectionEmpty: "Brak danych do porównania",
        bestPeriod: "Najlepszy okres",
        maxWinRate: "Max win rate",
        totalPeriods: "Liczba okresów",
        
        // Journal
        addTrade: "Dodaj transakcję",
        executedTrades: "Wykonane transakcje",
        plannedTrades: "Planowane transakcje",
        tradingAccount: "Konto tradingowe",
        symbol: "Symbol",
        direction: "Kierunek",
        timeframe: "Interwał",
        buy: "Kupno",
        sell: "Sprzedaż",
        statusLabel: "Status",
        openStatus: "Otwarte",
        closedStatus: "Zamknięte",
        plannedStatus: "Planowane",
        entry: "Wejście",
        exit: "Wyjście",
        entryTime: "Czas wejścia",
        exitTime: "Czas wyjścia",
        openPrice: "Cena otwarcia",
        closePrice: "Cena zamknięcia",
        lotSize: "Wielkość lota",
        profitLoss: "P&L",
        profitLossManualHint: "Wpisana wartość P&L nadpisuje wyliczenia",
        outcome: "Wynik",
        stopLossPips: "Stop Loss",
        takeProfitPips: "Take Profit",
        rr: "RR",
        quickSummary: "Szybkie podsumowanie",
        symbolAnalysis: "Analiza waluty",
        tradesCount: "Liczba transakcji",
        winRateLabel: "Win rate",
        avgPLLabel: "Średni P&L",
        screenshots: "Zrzuty",
        screenshot: "Zrzut",
        chooseScreenshotFolder: "Wybierz folder na zrzuty",
        folderSelected: "Folder wybrany",
        folderNotSelected: "Brak folderu",
        folderNotSupported: "Zapis do folderu nie jest wspierany w tej przegladarce",
        journalOfTrades: "Dziennik transakcji",
        planTrackYourTrades: "Planuj i śledź wszystkie swoje transakcje",
        all: "Wszystkie",
        planned: "Planowana",
        executed: "Wykonana",
        searchBySymbol: "Szukaj po symbolu...",
        allTime: "Cały czas",
        timeFilterActive: "Aktywny filtr czasu",
        noTradesToDisplay: "Brak transakcji do wyświetlenia",
        newTrade: "Nowa transakcja",
        editTrade: "Edytuj transakcję",
        markAsExecuted: "Oznacz jako wykonaną",
        viewDetails: "Zobacz szczegóły",
        
        // Accounts
        tradingAccounts: "Konta tradingowe",
        addAccount: "Dodaj konto",
        accountName: "Nazwa konta",
        broker: "Broker",
        accountType: "Typ konta",
        initialBalance: "Kapitał początkowy",
        currentBalance: "Aktualny kapitał",
        account: "Konto",
        manageAccountsMonitorResults: "Zarządzaj swoimi kontami i monitoruj wyniki",
        groupByType: "Grupuj wg typu",
        groupByBroker: "Grupuj wg brokera",
        accountsCount: "kont",
        noAccountsYet: "Nie masz jeszcze żadnych kont. Dodaj swoje pierwsze konto!",
        
        // Strategies
        tradingStrategies: "Strategie tradingowe",
        addStrategy: "Dodaj strategię",
        strategyName: "Nazwa strategii",
        category: "Kategoria",
        positionStatus: "Status",
        strategy: "Strategia",
        manageAnalyzeStrategies: "Zarządzaj i analizuj swoje strategie",
        noStrategiesYet: "Nie masz jeszcze żadnych strategii. Dodaj swoją pierwszą strategię!",
        
        // Goals
        financialGoals: "Cele finansowe",
        addGoal: "Dodaj cel",
        goalTitle: "Nazwa celu",
        targetValue: "Wartość docelowa",
        currentValue: "Aktualna wartość",
        defineTrackGoals: "Zdefiniuj i śledź swoje cele tradingowe",
        newGoal: "Nowy cel",
        editGoal: "Edytuj cel",
        createGoal: "Utwórz cel",
        goalName: "Nazwa celu",
        goalType: "Typ celu",
        monthlyProfit: "Miesięczny zysk",
        totalCapital: "Całkowity kapitał",
        profitFactorGoal: "Profit Factor",
        tradesCount: "Liczba transakcji",
        customGoal: "Własny cel",
        unit: "Jednostka",
        startDate: "Data rozpoczęcia",
        endDate: "Data zakończenia",
        statusActive: "Aktywny",
        statusCompleted: "Zakończony",
        statusFailed: "Nieudany",
        statusPaused: "Wstrzymany",
        lowPriority: "Niski",
        mediumPriority: "Średni",
        highPriority: "Wysoki",
        activeGoals: "Aktywne cele",
        completedGoals: "Zakończone cele",
        progress: "Postęp",
        noGoalsYet: "Nie masz jeszcze żadnych celów. Stwórz swój pierwszy cel!",
        to: "Do",
        lowPriorityLabel: "Niski priorytet",
        mediumPriorityLabel: "Średni priorytet",
        highPriorityLabel: "Wysoki priorytet",
        
        // Calendar
        today: "Dziś",
        thisMonth: "Ten miesiąc",
        trades: "Transakcje",
        tradingCalendar: "Kalendarz transakcji",
        browseTradesInCalendar: "Przeglądaj swoje transakcje w kalendarzu",
        selectDay: "Wybierz dzień",
        noTradesThisDay: "Brak transakcji tego dnia",
        clickDayToSee: "Kliknij na dzień aby zobaczyć transakcje",
        monthSummary: "Podsumowanie miesiąca",
        completedTrades: "Zakończone transakcje",
        noCompletedTrades: "Brak zakończonych transakcji w tym miesiącu",
        tradeDetails: "Szczegóły transakcji",
        transaction: "transakcja",
        transactions: "transakcje",
        open: "Otw",
        close: "Zam",
        position: "Pozycja",
        closes: "Zamknięć",
        
        // Days of week
        monday: "Pn",
        tuesday: "Wt",
        wednesday: "Śr",
        thursday: "Cz",
        friday: "Pt",
        saturday: "Sb",
        sunday: "Nd",

        // Position Manager
        positionManager: "Zarządzanie pozycją",
        positionManagerSubtitle: "Prosty, manualny moduł zarządzania transakcją",
        openManager: "Otwórz manager",
        hideManager: "Ukryj manager",
        useFormValues: "Użyj danych z formularza",
        entrySection: "Wejście",
        entryPrice: "Cena wejscie",
        phaseOne: "Faza 1: Otwarcie",
        phaseTwo: "Faza 2: Zarządzanie",
        phaseThree: "Faza 3: Zamknięcie",
        phaseEmpty: "Brak danych",
        slPrice: "SL",
        tpPrice: "TP",
        size: "Wielkość",
        riskDollar: "Ryzyko $",
        riskPercent: "Ryzyko %",
        rrLabel: "RR",
        potentialProfit: "Potencjalny zysk",
        setEntry: "Zapisz wejście",
        slManagement: "Zarządzanie SL",
        currentSl: "Aktualny SL",
        partialClose: "Częściowe zamknięcie",
        exitPrice: "Cena wyjścia",
        partialPercent: "% pozycji",
        applyPartial: "Zapisz partial",
        oneR: "1:1",
        closeAll: "Zamknij całość",
        exitPricePrompt: "Podaj cenę wyjścia",
        partialEvent: "Częściowe zamknięcie",
        slMovedEvent: "SL przesunięty do",
        closeEvent: "Zamknięcie",
        manualEvent: "Użyto wyniku manualnego",
        fullClose: "Pełne zamknięcie",
        closePrice: "Cena wyjścia",
        closePosition: "Zamknij pozycję",
        manualResult: "Wynik manualny",
        manualPnl: "Finalny P&L (manual)",
        useManual: "Użyj wyniku",
        clearManual: "Wyczyść",
        liveStats: "Statystyki na żywo",
        currentPrice: "Aktualna cena",
        realizedPnl: "Zrealizowany PnL",
        unrealizedPnl: "Niezrealizowany PnL",
        positionOpenPercent: "% pozycji otwarte",
        currentRR: "Aktualny RR",
        status: "Status",
        statusOPEN: "OTWARTA",
        statusPARTIAL: "CZĘŚCIOWA",
        statusCLOSED: "ZAMKNIĘTA",
        manualActive: "Użyty wynik manualny",
        history: "Historia",
        historyEmpty: "Brak zdarzeń",
        entryEvent: "Wejście",
        
        // Settings
        profile: "Profil",
        preferences: "Preferencje",
        trading: "Trading",
        notifications: "Powiadomienia",
        language: "Język",
        theme: "Motyw",
        logout: "Wyloguj się",

        // Home + Auth
        homeSubtitle: "Profesjonalny dziennik handlowy",
        homeDescription: "Śledź swoje transakcje, analizuj strategie i rozwijaj swoje umiejętności",
        homeLoginButton: "Zaloguj się",
        homeSecureLogin: "Bezpieczne logowanie szyfrowane end-to-end",
        homeAccessTo: "Uzyskaj dostęp do:",
        homeFeatureAnalysisTitle: "Analiza",
        homeFeatureAnalysisSubtitle: "Wyniki i raporty",
        homeFeatureJournalTitle: "Dziennik",
        homeFeatureJournalSubtitle: "Transakcje na osi",
        homeFeatureStrategiesTitle: "Strategie",
        homeFeatureStrategiesSubtitle: "Playbook setupow",
        loginWelcomeTitle: "Witaj ponownie",
        loginWelcomeDescription: "Zaloguj się, aby wrócić do swoich statystyk, strategii i pełnego dziennika transakcji.",
        loginTitle: "Zaloguj się",
        loginSubtitle: "Wprowadź swoje dane, aby uzyskać dostęp",
        loginEmailLabel: "Email",
        loginEmailPlaceholder: "twoj@email.com",
        loginPasswordLabel: "Hasło",
        loginPasswordPlaceholder: "••••••••",
        loginButton: "Zaloguj się",
        loginLoading: "Logowanie...",
        loginSeparator: "Lub zaloguj się przez",
        loginGoogleSoon: "Google login będzie wkrótce dostępny",
        loginMicrosoftSoon: "Microsoft login będzie wkrótce dostępny",
        loginNoAccount: "Nie masz konta?",
        loginRegisterLink: "Zarejestruj się",
        loginSuccess: "Zalogowano pomyślnie!",
        loginError: "Błąd logowania. Sprawdź dane i spróbuj ponownie.",
        loginInvalidCredentials: "Nieprawidłowy email lub hasło",
        registerTitle: "Utwórz konto",
        registerSubtitle: "Zarejestruj się w mniej niż minutę",
        registerHeroSubtitle: "Profesjonalny dziennik handlowy",
        registerHeroDescription: "Dołącz do społeczności traderów i zacznij śledzić swoje transakcje, analizować strategie i rozwijać umiejętności.",
        registerFullNameLabel: "Imię i nazwisko (opcjonalne)",
        registerFullNamePlaceholder: "Jan Kowalski",
        registerEmailLabel: "Email *",
        registerEmailPlaceholder: "twoj@email.com",
        registerPasswordLabel: "Hasło *",
        registerPasswordHint: "Minimum 6 znaków",
        registerConfirmPasswordLabel: "Potwierdź hasło *",
        registerButton: "Utwórz konto",
        registerLoading: "Tworzenie konta...",
        registerHaveAccount: "Masz już konto?",
        registerLoginLink: "Zaloguj się",
        registerSuccess: "Konto zostało utworzone! Witaj",
        registerError: "Błąd rejestracji. Spróbuj ponownie.",
        registerRequiredFields: "Wszystkie pola są wymagane",
        registerPasswordMismatch: "Hasła nie są identyczne",
        registerPasswordTooShort: "Hasło musi mieć co najmniej 6 znaków",
        registerInvalidEmail: "Nieprawidłowy format adresu email"
        ,
        registerEmailExists: "Użytkownik z tym adresem email już istnieje",
        
        // Public Navbar
        features: "Funkcje",
        pricing: "Cennik",
        about: "O nas",
        contact: "Kontakt",
        login: "Zaloguj się",
        register: "Zarejestruj się",
        
        // Footer
        footerTagline: "Profesjonalny dziennik handlowy dla poważnych traderów",
        footerNavigation: "Nawigacja",
        footerAccount: "Konto",
        footerLegal: "Regulamin",
        footerFollowUs: "Obserwuj nas",
        footerDisclaimer: "Ta aplikacja nie udziela porad inwestycyjnych. Handel wiąże się z ryzykiem. Wyniki z przeszłości nie wskazują na przyszłe rezultaty.",
        resetPassword: "Resetuj hasło",
        termsOfService: "Warunki korzystania",
        privacyPolicy: "Polityka prywatności",
        cookiesPolicy: "Polityka cookies"
      },
      en: {
        // Navigation
        dashboard: "Dashboard",
        journal: "Journal",
        notes: "My Notes",
        calendar: "Calendar",
        analytics: "Analytics",
        accounts: "Accounts",
        strategies: "Strategies",
        goals: "Goals",
        settings: "Settings",
        billing: "Billing",
        
        // Public Navbar
        features: "Features",
        pricing: "Pricing",
        about: "About",
        contact: "Contact",
        login: "Login",
        register: "Sign Up",
        
        // Footer
        footerTagline: "Professional trading journal for serious traders",
        footerNavigation: "Navigation",
        footerAccount: "Account",
        footerLegal: "Legal",
        footerFollowUs: "Follow Us",
        footerDisclaimer: "This application does not provide investment advice. Trading involves risk. Past performance is not indicative of future results.",
        resetPassword: "Reset Password",
        termsOfService: "Terms of Service",
        privacyPolicy: "Privacy Policy",
        cookiesPolicy: "Cookies Policy",
        
        // Common
        save: "Save",
        cancel: "Cancel",
        progressTracker: "Progress Tracker",
        edit: "Edit",
        delete: "Delete",
        add: "Add",
        added: "Added",
        remove: "Remove",
        change: "Change",
        view: "View",
        search: "Search",
        filter: "Filter",
        export: "Export",
        import: "Import",
        loading: "Loading...",
        noData: "No data",
        actions: "Actions",
        date: "Date",
        notes: "Notes",
        color: "Color",
        priority: "Priority",
        description: "Description",
        loadDataError: "Error loading data",
        userNotAuthenticated: "User not authenticated",
        requiredFieldsSymbolDate: "Please fill in required fields: Symbol, Date",
        requiredFieldsSymbolEntrySize: "Please fill in required fields: Symbol, Entry Price, Position Size",
        errorSavingTrade: "Error saving trade",
        selectAccountPlaceholder: "-- Select Account --",
        noAccountsAvailable: "No accounts available",
        selectStrategyPlaceholder: "-- Select Strategy --",
        noStrategiesAvailable: "No strategies available",
        notesPlaceholder: "General notes...",
        notesTitle: "My Notes",
        notesSubtitle: "Organize ideas, checklists, and plans in a modern workspace",
        notesNew: "New note",
        notesNewChecklist: "New checklist",
        notesNewPlan: "New plan",
        notesExport: "Export",
        notesImport: "Import",
        notesSearch: "Search notes, tasks, or tags...",
        notesAll: "All",
        notesNotes: "Notes",
        notesChecklists: "Checklists",
        notesPlans: "Plans",
        notesLibrary: "Library",
        notesPages: "Pages",
        notesStructure: "Structure",
        notesNotebooks: "Notebooks",
        notesSections: "Sections",
        notesSelectNotebook: "Select notebook",
        notesSelectSection: "Select section",
        notesNewNotebook: "New notebook",
        notesNewSection: "New section",
        notesRenameNotebook: "Rename notebook",
        notesRenameSection: "Rename section",
        notesDefaultNotebook: "Default notebook",
        notesDefaultSection: "General",
        notesAdd: "Add",
        notesAddPage: "Add page",
        notesAddSubpage: "Add subpage",
        notesAddSection: "Add section",
        notesDeleteSection: "Delete section",
        notesRenamePage: "Rename page",
        notesRenameSectionPrompt: "Enter a new section name",
        notesRenamePagePrompt: "Enter a new page name",
        notesEmpty: "No notes yet. Create your first note or plan.",
        notesUntitled: "Untitled",
        notesChecklistItems: "Checklist",
        notesNoPreview: "No preview",
        notesEditor: "Editor",
        notesPin: "Pin",
        notesUnpin: "Unpin",
        notesDelete: "Delete",
        notesSelect: "Select a note from the list or create a new one.",
        notesSelectFirst: "Select a note or create one first.",
        notesTitleLabel: "Title",
        notesTitlePlaceholder: "Note title",
        notesBody: "Body",
        notesBodyPlaceholder: "Write here. Capture ideas, plans, and checklists...",
        notesChecklist: "Checklist",
        notesAddTask: "Add task",
        notesChecklistEmpty: "No tasks yet. Add your first item.",
        notesTaskPlaceholder: "New task...",
        notesType_note: "Note",
        notesType_checklist: "Checklist",
        notesType_plan: "Plan",
        notesType: "Type",
        notesStatus: "Status",
        notesStatus_active: "Active",
        notesStatus_done: "Done",
        notesStatus_archived: "Archive",
        notesPriority: "Priority",
        notesPriority_low: "Low",
        notesPriority_medium: "Medium",
        notesPriority_high: "High",
        notesDueDate: "Due date",
        notesReminder: "Reminder",
        notesReminderSet: "Reminder set",
        notesReminderSent: "Reminder sent",
        notesReminderPermission: "Enable notifications to receive reminders",
        notesReminderFallback: "Reminder saved, but notifications are disabled",
        notesTags: "Tags",
        notesTagPlaceholder: "Add tag...",
        notesAddTag: "Add",
        notesNeedTag: "Enter a tag.",
        notesTagsEmpty: "No tags",
        notesRemoveTag: "Remove tag",
        notesLinks: "Links",
        notesLinkTitle: "Link title",
        notesLinkUrl: "URL",
        notesTableRows: "Enter number of rows",
        notesTableCols: "Enter number of columns",
        notesImageUrl: "Enter image URL",
        notesImageUploadError: "Failed to upload image",
        notesAttachments: "Attachments",
        notesAddAttachment: "Add file",
        notesAttachmentsEmpty: "No attachments",
        notesRemoveAttachment: "Remove",
        notesAttachmentUploadError: "Failed to upload file",
        notesAddLink: "Add link",
        notesNeedLink: "Enter a link URL.",
        notesLinksEmpty: "No links",
        notesNeedNotebookName: "Enter a notebook name.",
        notesNeedSectionName: "Enter a section name.",
        notesNewSectionPrompt: "Enter a new section name",
        notesNeedRenameSection: "Enter a new section name.",
        notesDeleteBlockedNotebook: "You cannot delete the last notebook.",
        notesDeleteBlockedSection: "You cannot delete the last section.",
        notesImportInvalid: "Invalid import file.",
        notesTaskDue: "Task due date",
        notesTaskNote: "Task note",
        notesViewList: "List",
        notesViewGrid: "Grid",
        notesViewTimeline: "Timeline",
        notesViewKanban: "Kanban",
        
        // Billing & Pricing
        billingTitle: "Trade Log Subscription",
        billingSubtitle: "Manage your plan and premium features",
        billingPlanDesc: "Full access to all trading features",
        billingPerMonth: "month",
        billing14DayTrial: "14 days free",
        billingIncluded: "What's included:",
        billingProFeature1: "Unlimited trade journal and analytics",
        billingProFeature2: "Advanced charts and performance reports",
        billingProFeature3: "Strategy and goal management",
        billingProFeature4: "AI-powered notes and checklists",
        billingProFeature5: "Data export and cloud backup",
        billingProFeature6: "Priority support 24/7",
        billingActive: "Active subscription",
        billingManage: "Manage subscription",
        billingStartTrial: "Start 14-day trial",
        billingNoCreditCard: "No credit card required to start trial",
        billingStatusTitle: "Subscription status",
        billingLoading: "Checking status...",
        billingStatus: "Status: {status}",
        billingMissingPrice: "Stripe price is not configured",
        billingCheckoutError: "Unable to open checkout",
        billingPortalError: "Unable to open billing portal",
        billingUpgradeNeeded: "This feature requires the Pro plan",
        
        // Pricing Page
        pricingBadge: "One simple price",
        pricingTitle: "Professional trading for $9.9/month",
        pricingSubtitle: "All the tools you need to grow as a trader. No hidden costs.",
        pricingPlanDesc: "Full access to all features",
        pricingPerMonth: "month",
        pricing14DayTrial: "14 days free - no card",
        pricingInclude1: "Unlimited trades and accounts",
        pricingInclude2: "Advanced P&L, win rate, and profit factor analysis",
        pricingInclude3: "Smart strategies and playbooks",
        pricingInclude4: "Trading psychology module and emotion journal",
        pricingInclude5: "Automatic backup and data export",
        pricingInclude6: "Premium support and regular updates",
        pricingStartTrial: "Start for free",
        pricingNoCreditCard: "No credit card needed for trial",
        pricingWhyChoose: "Why Trade Log?",
        pricingFeature1Title: "Complete performance analysis",
        pricingFeature1Desc: "Detailed statistics, equity charts, time analysis, and more",
        pricingFeature2Title: "Trading psychology",
        pricingFeature2Desc: "Track emotions, setup quality, and mental development",
        pricingFeature3Title: "Goal management",
        pricingFeature3Desc: "Set goals, monitor progress, and build consistency",
        pricingFeature4Title: "Strategies and playbooks",
        pricingFeature4Desc: "Document your setups and analyze their effectiveness",
        pricingFeature5Title: "Data security",
        pricingFeature5Desc: "End-to-end encryption and automatic backups",
        pricingFeature6Title: "Fast support",
        pricingFeature6Desc: "We respond within 24h and add new features regularly",
        pricingCTATitle: "Ready to grow?",
        pricingCTADesc: "Join hundreds of traders using Trade Log to build consistency and improve results.",
        pricingGetStarted: "Get started for free",
        
        // Dashboard
        totalPL: "Total P&L",
        winRate: "Win Rate",
        avgPL: "Average P&L",
        profitFactor: "Profit Factor",
        totalTrades: "Total Trades",
        wins: "Wins",
        losses: "Losses",
        breakeven: "Breakeven",
        bestTrade: "Best trade",
        worstTrade: "Worst trade",
        overviewOfYourTradingPerformance: "Overview of your trading performance",
        from: "From",
        perTrade: "Per trade",
        avgWinAvgLoss: "Avg Win / Avg Loss",
        avgWin: "Average Win",
        avgLoss: "Average Loss",
        averageWin: "Average Win",
        averageLoss: "Average Loss",
        totalTradesLabel: "Total Trades",
        plOverTime: "P&L Over Time",
        strategyPerformance: "Strategy Performance",
        select: "Select",
        myAccount: "My account",
        allAccounts: "All accounts",
        filters: "Filters",
        dateRange: "Date range",
        last7Days: "Last 7 days",
        last30Days: "Last 30 days",
        last90Days: "Last 90 days",
        lastImport: "Last import",
        resync: "Resync",
        startMyDay: "Start my day",
        reset: "Reset",
        apply: "Apply",
        dayWinRate: "Day win %",
        zellaScore: "Zella Score",
        tradingScore: "Trading Score",
        less: "Less",
        more: "More",
        dailyNetCumulativePL: "Daily net cumulative P&L",
        netDailyPL: "Net daily P&L",
        recentTrades: "Recent trades",
        netPL: "Net P&L",
        accountBalance: "Account balance",
        drawdown: "Drawdown",
        tradeTimePerformance: "Trade time performance",
        selectPlaceholder: "Select...",
        winRatePercent: "Win Rate (%)",
        detailedPLAnalysis: "Detailed P&L analysis",
        totalProfit: "Total profit",
        totalLoss: "Total loss",
        plByWeekday: "P&L by weekday",
        plBySymbol: "P&L by symbol",
        detailedWinRateAnalysis: "Detailed Win Rate analysis",
        ofAll: "of all",
        streaks: "Streaks",
        maxWins: "Max wins",
        maxLosses: "Max losses",
        winRateBySymbol: "Win Rate by symbol",
        winsShort: "W",
        lossesShort: "L",
        breakevenShort: "BE",
        detailedAvgPLAnalysis: "Detailed average P&L analysis",
        avgWinShort: "Avg win",
        avgLossShort: "Avg loss",
        medianWin: "Median win",
        medianLoss: "Median loss",
        avgPLByDirection: "Average P&L by direction",
        longLabel: "Long",
        shortLabel: "Short",
        detailedProfitFactorAnalysis: "Detailed Profit Factor analysis",
        pfExcellent: "Excellent",
        pfGood: "Good",
        pfAcceptable: "Acceptable",
        pfNeedsImprovement: "Needs improvement",
        tradeEfficiency: "Trade efficiency",
        detailedOutcomeAnalysis: "Detailed outcome distribution analysis",
        distributionByTimeframe: "Distribution by timeframe",
        zellaWinRate: "Win %",
        zellaProfit: "Profit",
        zellaConsistency: "Consistency",
        zellaDrawdown: "Drawdown",
        zellaAvgWL: "Avg W/L",
        
        // Journal
        addTrade: "Add Trade",
        executedTrades: "Executed Trades",
        plannedTrades: "Planned Trades",
        tradingAccount: "Trading Account",
        symbol: "Symbol",
        direction: "Direction",
        timeframe: "Timeframe",
        buy: "Buy",
        sell: "Sell",
        statusLabel: "Status",
        openStatus: "Open",
        closedStatus: "Closed",
        plannedStatus: "Planned",
        entry: "Entry",
        exit: "Exit",
        entryTime: "Entry Time",
        exitTime: "Exit Time",
        openPrice: "Open Price",
        closePrice: "Close Price",
        lotSize: "Lot Size",
        profitLoss: "P&L",
        profitLossManualHint: "Manual P&L overrides calculated value",
        outcome: "Outcome",
        stopLossPips: "Stop Loss",
        takeProfitPips: "Take Profit",
        rr: "RR",
        quickSummary: "Quick Summary",
        symbolAnalysis: "Currency analysis",
        tradesCount: "Trades count",
        winRateLabel: "Win rate",
        avgPLLabel: "Average P&L",
        screenshots: "Screenshots",
        screenshot: "Screenshot",
        chooseScreenshotFolder: "Choose screenshots folder",
        folderSelected: "Folder selected",
        folderNotSelected: "No folder selected",
        folderNotSupported: "Folder saving is not supported in this browser",
        journalOfTrades: "Trade Journal",
        planTrackYourTrades: "Plan and track all your trades",
        all: "All",
        planned: "Planned",
        executed: "Executed",
        searchBySymbol: "Search by symbol...",
        allTime: "All time",
        timeFilterActive: "Time filter active",
        noTradesToDisplay: "No trades to display",
        newTrade: "New Transaction",
        editTrade: "Edit Trade",
        markAsExecuted: "Mark as executed",
        viewDetails: "View details",
        
        // Accounts
        tradingAccounts: "Trading Accounts",
        addAccount: "Add Account",
        accountName: "Account Name",
        broker: "Broker",
        accountType: "Account Type",
        initialBalance: "Initial Balance",
        currentBalance: "Current Balance",
        account: "Account",
        manageAccountsMonitorResults: "Manage your accounts and monitor results",
        groupByType: "Group by type",
        groupByBroker: "Group by broker",
        accountsCount: "accounts",
        noAccountsYet: "You don't have any accounts yet. Add your first account!",
        
        // Strategies
        tradingStrategies: "Trading Strategies",
        addStrategy: "Add Strategy",
        strategyName: "Strategy Name",
        category: "Category",
        status: "Status",
        strategy: "Strategy",
        manageAnalyzeStrategies: "Manage and analyze your strategies",
        noStrategiesYet: "You don't have any strategies yet. Add your first strategy!",
        
        // Goals
        financialGoals: "Financial Goals",
        addGoal: "Add Goal",
        goalTitle: "Goal Title",
        targetValue: "Target Value",
        currentValue: "Current Value",
        defineTrackGoals: "Define and track your trading goals",
        newGoal: "New Goal",
        editGoal: "Edit Goal",
        createGoal: "Create Goal",
        goalName: "Goal Name",
        goalType: "Goal Type",
        monthlyProfit: "Monthly Profit",
        totalCapital: "Total Capital",
        profitFactorGoal: "Profit Factor",
        tradesCount: "Number of Trades",
        customGoal: "Custom Goal",
        unit: "Unit",
        startDate: "Start Date",
        endDate: "End Date",
        statusActive: "Active",
        statusCompleted: "Completed",
        statusFailed: "Failed",
        statusPaused: "Paused",
        lowPriority: "Low",
        mediumPriority: "Medium",
        highPriority: "High",
        activeGoals: "Active Goals",
        completedGoals: "Completed Goals",
        progress: "Progress",
        noGoalsYet: "You don't have any goals yet. Create your first goal!",
        to: "To",
        lowPriorityLabel: "Low priority",
        mediumPriorityLabel: "Medium priority",
        highPriorityLabel: "High priority",
        
        // Calendar
        today: "Today",
        thisMonth: "This Month",
        trades: "Trades",
        tradingCalendar: "Trading Calendar",
        browseTradesInCalendar: "Browse your trades in calendar",
        selectDay: "Select a day",
        noTradesThisDay: "No trades this day",
        clickDayToSee: "Click on a day to see trades",
        monthSummary: "Month Summary",
        completedTrades: "Completed Trades",
        noCompletedTrades: "No completed trades this month",
        tradeDetails: "Trade Details",
        transaction: "Trade",
        transactions: "Trades",
        open: "Open",
        close: "Close",
        position: "Position",
        closes: "Closes",
        
        // Days of week
        monday: "Mon",
        tuesday: "Tue",
        wednesday: "Wed",
        thursday: "Thu",
        friday: "Fri",
        saturday: "Sat",
        sunday: "Sun",
        
        // Analytics
        advancedAnalytics: "Advanced Analytics",
        detailedAnalysisOfAllAspects: "Detailed analysis of all trading aspects",
        allAccounts: "All accounts",
        overview: "Overview",
        symbols: "Symbols",
        strategiesAnalytics: "Strategies",
        accountsAnalytics: "Accounts",
        psychology: "Psychology",
        outcomeDistribution: "Outcome Distribution",
        directionDistribution: "Direction Distribution",
        equityCurve: "Equity Curve",
        results: "Results",
        weekly: "Weekly",
        monthly: "Monthly",
        yearly: "Yearly",
          longVsShort: "Long vs Short",
        timeframeAnalysis: "Timeframe Analysis",
        sessionsAnalysis: "Trading Sessions Analysis",
        avgPLLabel: "Avg P&L",
        top10Symbols: "Top 10 Symbols by P&L",
        totalPLLabel: "Total P&L",
        noOfTrades: "Trades",
        detailedAnalysisSymbol: "Detailed Analysis",
        byAccounts: "By Accounts",
        byStrategies: "By Strategies",
        byTimeframe: "By Timeframe",
        bestTradeSingle: "Best Trade",
        worstTradeSingle: "Worst Trade",
        setup: "Setup",
        strategiesComparison: "Strategy Comparison",
        accountsComparison: "Accounts Comparison",
        roi: "ROI",
        setupQuality: "Setup Quality",
        emotionalState: "Emotional State",
        setupQualityDetails: "Setup Quality Details",
        emotionalAnalysis: "Emotional Analysis",
        avg: "Avg",
        noStrategy: "No strategy",
        unknown: "Unknown",
        bySymbols: "By Symbols",
        weekly: "Weekly",
        monthly: "Monthly",
        yearly: "Yearly",
        daily: "Daily",
        insightOutcomeMost: "Most outcomes:",
        insightOutcomeEmpty: "Not enough data for insights",
        insightDirectionBest: "Best direction:",
        insightDirectionEmpty: "Not enough data to compare",
        bestPeriod: "Best period",
        maxWinRate: "Max win rate",
        totalPeriods: "Total periods",

        // Position Manager
        positionManager: "Position Manager",
        positionManagerSubtitle: "Simple, manual position management module",
        openManager: "Open manager",
        hideManager: "Hide manager",
        useFormValues: "Use form values",
        entrySection: "Entry",
        entryPrice: "Entry",
        phaseOne: "Phase 1: Entry",
        phaseTwo: "Phase 2: Management",
        phaseThree: "Phase 3: Close",
        phaseEmpty: "No data",
        slPrice: "SL",
        tpPrice: "TP",
        size: "Size",
        riskDollar: "Risk $",
        riskPercent: "Risk %",
        rrLabel: "RR",
        potentialProfit: "Potential profit",
        setEntry: "Set entry",
        slManagement: "SL management",
        currentSl: "Current SL price",
        partialClose: "Partial close",
        exitPrice: "Exit price",
        partialPercent: "% size",
        applyPartial: "Apply partial",
        oneR: "1:1",
        closeAll: "Close all",
        exitPricePrompt: "Enter exit price",
        partialEvent: "Partial close",
        slMovedEvent: "SL moved to",
        closeEvent: "Close",
        manualEvent: "Manual result used",
        fullClose: "Full close",
        closePrice: "Close price",
        closePosition: "Close position",
        manualResult: "Manual result",
        manualPnl: "Final P&L (manual)",
        useManual: "Use manual",
        clearManual: "Clear",
        liveStats: "Live stats",
        currentPrice: "Current price",
        realizedPnl: "Realized PnL",
        unrealizedPnl: "Unrealized PnL",
        positionOpenPercent: "% open",
        currentRR: "Current RR",
        positionStatus: "Status",
        statusOPEN: "OPEN",
        statusPARTIAL: "PARTIAL",
        statusCLOSED: "CLOSED",
        manualActive: "Manual result active",
        history: "History",
        historyEmpty: "No events yet",
        entryEvent: "Entry",
        
        // Settings
        profile: "Profile",
        preferences: "Preferences",
        trading: "Trading",
        notifications: "Notifications",
        language: "Language",
        theme: "Theme",
        logout: "Log Out",

        // Home + Auth
        homeSubtitle: "Professional trading journal",
        homeDescription: "Track your trades, analyze strategies, and grow your edge",
        homeLoginButton: "Log In",
        homeSecureLogin: "Secure end-to-end encrypted login",
        homeAccessTo: "Get access to:",
        homeFeatureAnalysisTitle: "Analysis",
        homeFeatureAnalysisSubtitle: "Results and reports",
        homeFeatureJournalTitle: "Journal",
        homeFeatureJournalSubtitle: "Trades on the timeline",
        homeFeatureStrategiesTitle: "Strategies",
        homeFeatureStrategiesSubtitle: "Setup playbooks",
        loginWelcomeTitle: "Welcome back",
        loginWelcomeDescription: "Log in to return to your stats, strategies, and full trade journal.",
        loginTitle: "Log In",
        loginSubtitle: "Enter your details to access your account",
        loginEmailLabel: "Email",
        loginEmailPlaceholder: "you@email.com",
        loginPasswordLabel: "Password",
        loginPasswordPlaceholder: "••••••••",
        loginButton: "Log In",
        loginLoading: "Signing in...",
        loginSeparator: "Or sign in with",
        loginGoogleSoon: "Google login will be available soon",
        loginMicrosoftSoon: "Microsoft login will be available soon",
        loginNoAccount: "Don't have an account?",
        loginRegisterLink: "Create one",
        loginSuccess: "Logged in successfully!",
        loginError: "Login failed. Check your details and try again.",
        loginInvalidCredentials: "Invalid email or password",
        registerTitle: "Create account",
        registerSubtitle: "Sign up in less than a minute",
        registerHeroSubtitle: "Professional trading journal",
        registerHeroDescription: "Join the trading community and start tracking trades, analyzing strategies, and building skill.",
        registerFullNameLabel: "Full name (optional)",
        registerFullNamePlaceholder: "Jane Doe",
        registerEmailLabel: "Email *",
        registerEmailPlaceholder: "you@email.com",
        registerPasswordLabel: "Password *",
        registerPasswordHint: "Minimum 6 characters",
        registerConfirmPasswordLabel: "Confirm password *",
        registerButton: "Create account",
        registerLoading: "Creating account...",
        registerHaveAccount: "Already have an account?",
        registerLoginLink: "Log in",
        registerSuccess: "Account created! Welcome",
        registerError: "Registration failed. Please try again.",
        registerRequiredFields: "All fields are required",
        registerPasswordMismatch: "Passwords do not match",
        registerPasswordTooShort: "Password must be at least 6 characters",
        registerInvalidEmail: "Invalid email format",
        registerEmailExists: "An account with this email already exists"
      }
    };
    
    setTranslations(allTranslations[lang] || allTranslations.pl);
    localStorage.setItem("appLanguage", lang);
  }, [language]);

  // Initialize from user preferences on mount
  useEffect(() => {
    if (user?.language) {
      const normalized = normalizeLanguage(user.language);
      if (normalized !== language) {
        setLanguage(normalized);
      }
    }
    setIsLoading(false);
  }, [user?.language]);

  const t = (key) => {
    return translations[key] || key;
  };

  const updateLanguage = (newLang) => {
    const normalized = normalizeLanguage(newLang);
    setLanguage(normalized);
    
    // Update user preferences in database
    if (user?.id) {
      try {
        updateUser(user.id, { language: normalized });
        if (checkSession) {
          setTimeout(() => checkSession(), 100);
        }
      } catch (error) {
        console.error('Failed to update language:', error);
      }
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: updateLanguage, t, isLoading }}>
      {children}
    </LanguageContext.Provider>
  );
}